import { Inter } from "next/font/google";
import "./globals.css";
import AppContextProvider from "@/Context/AppContext";
import { AuthProvider } from "@/Context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Safal Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ico.png" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <AppContextProvider>{children}</AppContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
