import { Inter } from "next/font/google";
import "./globals.css";
import AppContextProvider from "@/Context/AppContext";
import { AuthProvider } from "@/Context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <AppContextProvider>
          <body className={inter.className}>{children}</body>
        </AppContextProvider>
      </AuthProvider>
    </html>
  );
}
